package SwingClient;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JScrollBar;

/**
 *
 * @author sam
 */
public class ChatPanel extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form ChatPanel
     */
    public ChatPanel() {
        initComponents();
        MainFrame.client.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        chatLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        sndButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(227, 242, 253));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(340, 525));

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(null);
        scrollPane.setForeground(new java.awt.Color(255, 255, 255));
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        chatLabel.setBackground(new java.awt.Color(255, 255, 255));
        chatLabel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        chatLabel.setForeground(new java.awt.Color(100, 100, 100));
        chatLabel.setText("<html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
        chatLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        chatLabel.setAutoscrolls(true);
        chatLabel.setOpaque(true);
        scrollPane.setViewportView(chatLabel);

        titleLabel.setBackground(new java.awt.Color(0, 62, 135));
        titleLabel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 28)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText(" Messages");
        titleLabel.setOpaque(true);

        textField.setBackground(new java.awt.Color(230, 230, 230));
        textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldKeyPressed(evt);
            }
        });

        sndButton.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        sndButton.setForeground(new java.awt.Color(1, 104, 184));
        sndButton.setText("Send");
        sndButton.setBorder(null);
        sndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sndButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(227, 242, 253));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 62, 135));
        jLabel1.setText("  Destinations");
        jLabel1.setOpaque(true);

        jScrollPane1.setBackground(new java.awt.Color(227, 242, 253));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(227, 242, 253));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sndButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(textField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyPressed
        if (evt.getKeyCode() == 10) {
            sendMsg();
        }
    }//GEN-LAST:event_textFieldKeyPressed

    private void sndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sndButtonActionPerformed
        sendMsg();
    }//GEN-LAST:event_sndButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chatLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton sndButton;
    private javax.swing.JTextField textField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        String msg = MainFrame.client.getMsg();
        if (!msg.startsWith("0x000")) {
            msg = "<center>" + msg.substring(5) + "</center>";
        } else {
            msg = "<div style=\"margin-left: 5px;\">" + msg.substring(5) + "</div>";
            msg = cutMsg(msg);
        }
        chatLabel.setText(chatLabel.getText() + "<br>" + msg);
        JScrollBar scroll = scrollPane.getVerticalScrollBar();
        scroll.setValue(scroll.getMaximum());
    }
    
    /**
     * Send message to server
     */
    public void sendMsg() {
        try {
            MainFrame.client.getPw().println(textField.getText());
        } catch (Exception e) {
            System.out.println(e);
        }
        chatLabel.setText(chatLabel.getText() + 
                "<br><div align=\"right\" style=\"margin-right: 10px;\">" + 
                cutMsg(textField.getText()) + "</div>");
        textField.setText("");
        JScrollBar scroll = scrollPane.getVerticalScrollBar();
        scroll.setValue(scroll.getMaximum());
    }
    
    /**
     * add a "brake line" tag if message is too long
     * @param msg
     * @return 
     */
    public String cutMsg(String msg) {
        String ret = "";
        for (int i = 0; i < msg.length(); i++) {
            ret += msg.charAt(i);
            if ((i+1) % 30 == 0) {
                ret += "<br>";
            }
        }
        return ret;
    }
}
